services:
  # Backend Service Configuration
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    ports:
      - "4000:4000"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    env_file:
      - ./Backend/.env
    # This setting allows the container to connect to services on the host machine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis # Still depends on the Redis container
    networks:
      - ecommerce-network

  # Frontend Service Configuration
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - ecommerce-network

  # Redis Service Configuration (MongoDB service is removed)
  redis:
    image: redis:latest
    container_name: ecommerce-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ecommerce-network

# Volumes configuration for Redis data persistence
volumes:
  redis-data:

# Network configuration for inter-service communication
networks:
  ecommerce-network:
    driver: bridge

